FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y python3 python3-pip python3-opencv #python3-numpy
RUN pip3 install scikit-learn tqdm tensorflow numpy==1.22 keras matplotlib opencv-python

# Set the working directory
WORKDIR /work

# Add the data
ADD traffic_sign_seq_highaccuracy.h5 /work
ADD frame206.jpg /work
#RUN unzip data.zip

# Add python-script
COPY Traffic_sign_classification-checkpoint-highinference.py /work

ENTRYPOINT ["python3", "Traffic_sign_classification-checkpoint-highinference.py"]
